var data=[
  { category: 'movie', age: 'teenager', visitors: 66 },
  { category: 'education', age: 'adult', visitors: 66 },
  { category: 'news', age: 'adult', visitors: 66 },
  { category: 'politics', age: 'teenager', visitors: 80 },
  { category: 'education', age: 'teenager', visitors: 65 },
  { category: 'news', age: 'adult', visitors: 89 },
  { category: 'news', age: 'teenager', visitors: 39 },
  { category: 'sports ', age: 'teenager', visitors: 64 },
  { category: 'politics', age: 'adult', visitors: 16 },
  { category: 'education', age: 'adult', visitors: 48 },
  { category: 'movie', age: 'adult', visitors: 33 },
  { category: 'news', age: 'adult', visitors: 1 },
  { category: 'news', age: 'adult', visitors: 80 },
  { category: 'news', age: 'adult', visitors: 14 },
  { category: 'education', age: 'teenager', visitors: 69 },
  { category: 'sports ', age: 'adult', visitors: 56 },
  { category: 'news', age: 'teenager', visitors: 7 },
  { category: 'politics', age: 'adult', visitors: 27 },
  { category: 'news', age: 'teenager', visitors: 68 },
  { category: 'education', age: 'teenager', visitors: 12 },
  { category: 'sports ', age: 'teenager', visitors: 57 },
  { category: 'sports ', age: 'adult', visitors: 95 },
  { category: 'movie', age: 'adult', visitors: 35 },
  { category: 'sports ', age: 'teenager', visitors: 42 },
  { category: 'movie', age: 'teenager', visitors: 52 },
  { category: 'politics', age: 'adult', visitors: 55 },
  { category: 'politics', age: 'adult', visitors: 25 },
  { category: 'politics', age: 'adult', visitors: 42 },
  { category: 'movie', age: 'adult', visitors: 1 },
  { category: 'politics', age: 'teenager', visitors: 74 },
  { category: 'news', age: 'teenager', visitors: 34 },
  { category: 'sports ', age: 'teenager', visitors: 33 },
  { category: 'politics', age: 'teenager', visitors: 22 },
  { category: 'education', age: 'adult', visitors: 70 },
  { category: 'education', age: 'teenager', visitors: 69 },
  { category: 'movie', age: 'teenager', visitors: 53 },
  { category: 'politics', age: 'adult', visitors: 3 },
  { category: 'sports ', age: 'teenager', visitors: 99 },
  { category: 'movie', age: 'teenager', visitors: 37 },
  { category: 'education', age: 'teenager', visitors: 20 },
  { category: 'politics', age: 'adult', visitors: 80 },
  { category: 'movie', age: 'adult', visitors: 68 },
  { category: 'politics', age: 'adult', visitors: 67 },
  { category: 'politics', age: 'adult', visitors: 37 },
  { category: 'education', age: 'teenager', visitors: 92 },
  { category: 'movie', age: 'teenager', visitors: 51 },
  { category: 'news', age: 'teenager', visitors: 28 },
  { category: 'news', age: 'teenager', visitors: 10 },
  { category: 'sports ', age: 'teenager', visitors: 48 },
  { category: 'movie', age: 'teenager', visitors: 14 },
  { category: 'politics', age: 'teenager', visitors: 19 },
  { category: 'politics', age: 'teenager', visitors: 22 },
  { category: 'politics', age: 'adult', visitors: 84 },
  { category: 'movie', age: 'adult', visitors: 67 },
  { category: 'politics', age: 'teenager', visitors: 14 },
  { category: 'sports ', age: 'teenager', visitors: 15 },
  { category: 'politics', age: 'adult', visitors: 14 },
  { category: 'news', age: 'teenager', visitors: 58 },
  { category: 'education', age: 'teenager', visitors: 45 },
  { category: 'politics', age: 'teenager', visitors: 82 },
  { category: 'education', age: 'teenager', visitors: 58 },
  { category: 'politics', age: 'teenager', visitors: 10 },
  { category: 'education', age: 'adult', visitors: 56 },
  { category: 'news', age: 'teenager', visitors: 83 },
  { category: 'politics', age: 'adult', visitors: 76 },
  { category: 'movie', age: 'teenager', visitors: 12 },
  { category: 'movie', age: 'adult', visitors: 76 },
  { category: 'movie', age: 'teenager', visitors: 43 },
  { category: 'movie', age: 'teenager', visitors: 75 },
  { category: 'education', age: 'teenager', visitors: 66 },
  { category: 'politics', age: 'adult', visitors: 77 },
  { category: 'news', age: 'teenager', visitors: 23 },
  { category: 'politics', age: 'adult', visitors: 83 },
  { category: 'news', age: 'teenager', visitors: 95 },
  { category: 'education', age: 'teenager', visitors: 57 },
  { category: 'sports ', age: 'adult', visitors: 43 },
  { category: 'sports ', age: 'adult', visitors: 95 },
  { category: 'sports ', age: 'adult', visitors: 44 },
  { category: 'education', age: 'teenager', visitors: 41 },
  { category: 'movie', age: 'adult', visitors: 44 },
  { category: 'news', age: 'teenager', visitors: 23 },
  { category: 'movie', age: 'teenager', visitors: 21 },
  { category: 'news', age: 'adult', visitors: 86 },
  { category: 'movie', age: 'adult', visitors: 84 },
  { category: 'politics', age: 'adult', visitors: 48 },
  { category: 'sports ', age: 'adult', visitors: 13 },
  { category: 'sports ', age: 'adult', visitors: 15 },
  { category: 'movie', age: 'teenager', visitors: 30 },
  { category: 'education', age: 'teenager', visitors: 77 },
  { category: 'movie', age: 'teenager', visitors: 69 },
  { category: 'sports ', age: 'adult', visitors: 86 },
  { category: 'politics', age: 'teenager', visitors: 31 },
  { category: 'movie', age: 'adult', visitors: 30 },
  { category: 'movie', age: 'teenager', visitors: 65 },
  { category: 'sports ', age: 'adult', visitors: 32 },
  { category: 'education', age: 'teenager', visitors: 16 },
  { category: 'politics', age: 'teenager', visitors: 68 },
  { category: 'movie', age: 'teenager', visitors: 68 },
  { category: 'politics', age: 'adult', visitors: 1 },
  { category: 'movie', age: 'teenager', visitors: 89 }
]
/*let ageint=[];
for(let i=0;i<15;i++)
{
  ageint= parseInt(data[i]);

}
console.log((ageint * 100)/data.length + "%");
*/

function percentage(obj)
{
var sum=0;
for(var i in obj){
  
}
}